import { Button } from "std-widgets.slint";
import { ComboInput, RadioButtonGroup } from "components.slint";

export component ImpPage inherits Rectangle {
	Image {
		source: @image-url("../assets/impedanc.jpg");
		image-fit: fill; 
		opacity: 0.3;
		width: root.width;
		height: root.height;
	}

	callback go_back;
	callback toggled(int);

	in property <[string]> l-model;
	in property <[string]> c-model;
	in property <[string]> f-model;

	VerticalLayout {
		alignment: space-around;

		Text {
			text: "IMP Calcularoty";
			horizontal-alignment: center;
			font-size: 30px;
		}

		l-input := ComboInput {
			combobox-model: l-model;
		}

		c-input := ComboInput {
			combobox-model: c-model;
		}

		f-input := ComboInput {
			combobox-model: f-model;
		}

		RadioButtonGroup {
			labels: ["ya", "no"];
			toggled(i) => { toggled(i) }
		}
		
		VerticalLayout {
			spacing: 20px;
			HorizontalLayout {
				alignment: center;
				Button {
					text: "Calcularot";
					width: 150px;
					clicked => { }
				}
			}
			HorizontalLayout {
				alignment: center;
				Button {
					text: "Escape";
					width: 150px;
					clicked => { go_back() }
				}
			}
		}
	}
}
