import { ComboInput } from "components.slint";
import { Button } from "std-widgets.slint";

export component LcPage inherits Image {
	source: @image-url("../assets/resonan.jpg");
	image-fit: fill;

		
	in property <[string]> input1-model;
	in property <[string]> input2-model;
	in property <[string]> input3-model;

	in-out property <string> input1-combo-text <=> input1.combo-value;
	in-out property <string> input2-combo-text <=> input2.combo-value;

	in property <string> output_text;

	callback go_back;
	callback calcularot(string, string, string, string, string);
	callback input1-combo-changed(string);
	callback input2-combo-changed(string);

	VerticalLayout {
		padding-top: 10px;
		padding-bottom: 10px;
		padding-right: 20px;
		padding-left: 20px;
		alignment: space-around;

		Text {
			text: "LC Calcularoty";
			stroke: black;
			stroke-width: 3px;
			font-size: 30px;
			horizontal-alignment: center;
		}
		input1 := ComboInput {
			combobox-model: input1-model;
			input-type: decimal;
			combo_changed(value) => { input1-combo-changed(value) }
		}
		input2 := ComboInput {
			combobox-model: input2-model;
			input-type: decimal;
			combo_changed(value) => { input2-combo-changed(value) }
		}
		output := ComboInput {
			combobox-model: input3-model;
			read-only: true;
			input-text: output_text;
		}
		VerticalLayout {
			spacing: 20px;
			HorizontalLayout {
				alignment: center;
				Button {
					text: "Calcularot";
					width: 150px;
					clicked => { calcularot(
						input1.combo-value,
						input2.combo-value,
						output.combo-value,
						input1.input-text,
						input2.input-text
					)}
				}
			}
			HorizontalLayout {
				alignment: center;
				Button {
					text: "Escape";
					width: 150px;
					clicked => { go_back() }
				}
			}
		}
	}
}
