import { Button } from "std-widgets.slint";

export component MenuPage inherits Rectangle {
	Image {
		source: @image-url("../assets/calcularoty.jpg");
		image-fit: fill;
		opacity: 0.3;
		width: root.width;
		height: root.height;
	}

	callback goto_lc;
	callback goto_imp;

	
	VerticalLayout {
		alignment: space-around;
		Text {
			text: "The Calcularoty";
			horizontal-alignment: center;
			font-size: 30px;
			font-weight: 800;
			color: white;
		}
		HorizontalLayout {
			alignment: center;
			Button {
				text: "LC Calcularoty";
				width: 250px;
				clicked => { goto_lc() }
			}
		}
		HorizontalLayout {
			alignment: center;
			Button {
				text: "IMP Calcularoty";
				width: 250px;
				clicked => { goto_imp() }
			}
		}
	}
}
